# Generated by Django 4.2 on 2023-11-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
