# Generated by Django 4.2 on 2023-12-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="description",
            field=models.TextField(default="about you"),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(default="first name", max_length=50),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(default="last name", max_length=50),
        ),
        migrations.AlterField(
            model_name="users",
            name="photo",
            field=models.ImageField(
                default="media/user_images/no_profile.png", upload_to="user_images"
            ),
        ),
    ]
