# Generated by Django 4.2 on 2023-12-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name_company',
            new_name='company_name',
        ),
    ]
