# Generated by Django 4.2 on 2023-12-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_users_description_alter_users_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="photo",
            field=models.ImageField(
                default="user_images/no_profile.png", upload_to="user_images"
            ),
        ),
    ]
