# Generated by Django 4.2 on 2023-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_name_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
