# Generated by Django 4.2 on 2024-01-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0003_rename_name_images_title"),
        ("users", "0004_alter_users_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="favourites",
            field=models.ManyToManyField(blank=True, null=True, to="animals.animals"),
        ),
        migrations.AddField(
            model_name="users",
            name="quantity_favourites",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="users",
            name="quantity_form",
            field=models.IntegerField(default=0),
        ),
    ]
