# Generated by Django 4.2 on 2024-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0003_rename_name_images_title"),
        ("users", "0005_users_favourites_users_quantity_favourites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="forms",
            field=models.ManyToManyField(
                blank=True, null=True, to="animals.formanimals"
            ),
        ),
    ]
