# Generated by Django 4.2 on 2024-01-04 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_users_forms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="quantity_form",
            new_name="quantity_forms",
        ),
    ]
