# Generated by Django 4.2 on 2023-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                ("species", models.CharField(max_length=200, verbose_name="Порода")),
                ("age", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="animals_images")),
            ],
            options={
                "verbose_name": "животное",
                "verbose_name_plural": "Животные",
            },
        ),
    ]
