# Generated by Django 4.2 on 2023-11-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                ("species", models.CharField(max_length=200, verbose_name="Порода")),
                ("age", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.companies",
                    ),
                ),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.images",
                    ),
                ),
            ],
            options={
                "verbose_name": "животное",
                "verbose_name_plural": "Животные",
            },
        ),
    ]
