# Generated by Django 4.2 on 2023-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animals",
            name="images",
        ),
        migrations.AddField(
            model_name="animals",
            name="images",
            field=models.ManyToManyField(to="companies.images"),
        ),
    ]
