# Generated by Django 4.2 on 2023-12-28 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="name",
            new_name="title",
        ),
    ]
