# Generated by Django 4.2 on 2023-12-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images'),
        ),
    ]
